# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1187c212db79e5891e36f357ddddf395c300786b82c9c53fa99659a7eb99cba42af3fcacf96b2211ec0143f75067997f16d1785adce1e524f93721e5a1855895

test:
  secret_key_base: 95b7dea9cd1e8ff9134aa6f35cee933efa9f1bcc8d0e923d6da2b8edf3545ca9622550938f7a72d573036cc630806a7375e7be455c61dabedcd16a8b68ef4114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
